version: "3.8"

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiZjJlOWJkZTYzZDEyZTUzZDlhYTNkOTNiZTNhZTBlODkiLCJ0IjoiYzA2ZTNhNTItZTIwOS00YTQ1LThmNGYtMTI4MDdiYmFiMjE2IiwicyI6IlpXRTFNREJrT1dVdFlXWTNNUzAwWW1NNExUazBNamd0WTJNd05UaGlZVFpsTVdVMyJ9
    restart: unless-stopped
